version: '3'

services:
  php:
    build: ./php
    privileged: true
    environment: 
      - APACHE_RUN_USER=#1000
    volumes:
      - ./src:/var/www/html


  nginx:
    image: nginx:latest
    
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      
    volumes:
      - ./mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3307:3306



        # image: mysql:5.7
        # restart: always
        # environment:
        #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        #     MYSQL_DATABASE: wpbaa
        #     MYSQL_USER: ${MYSQL_USER}
        #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        # volumes: 
        #     - ${DB_PATH_HOST}:/var/lib/mysql
        # command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        # ports:
        #     - 3307:3306
        # networks: 
        #     - wpsite